name: Deploy PHP Site

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Только для main ветки

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ vars.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        run: |
          rsync -avz --delete \
            --exclude=".git/" \
            --exclude=".github/" \
            --exclude="uploads/" \
            ./ ${{ secrets.SSH_USER }}@${{ vars.SERVER_HOST }}:/var/www/html/

      - name: Cleanup SSH key
        run: rm -f ~/.ssh/id_rsa